#!/bin/bash

selected=$(bluetoothctl devices Paired | dmenu -i -l 10 -p "Connect to: " | awk '{print $2}')

if [ -z "$selected" ]; then
    exit 0
fi

is_connected=$(bluetoothctl info $selected | grep "Connected: yes")

if [ -z "$is_connected" ]; then
    bluetoothctl connect $selected
else
    bluetoothctl disconnect $selected
fi

