#!/bin/bash

time="$1"
shift
cmd="$@"

# Start the command in the background
$cmd &
pid=$!

SECONDS=0
while [ $SECONDS -lt $time ]; do
    # If the process already finished, exit
    kill -0 $pid 2>/dev/null || exit 0
    sleep 1
done

kill $pid
