#!/bin/bash -v

#####################################################
#  m    m            #           m                  #
#  #    # mmmm    mmm#   mmm   mm#mm   mmm    mmm   #
#  #    # #" "#  #" "#  "   #    #    #"  #  #   "  #
#  #    # #   #  #   #  m"""#    #    #""""   """m  #
#  "mmmm" ##m#"  "#m##  "mm"#    "mm  "#mm"  "mmm"  #
#         #                                         #
#         "                                         #
#####################################################

nvim -c "PlugUpdate"
sudo nala upgrade
sudo snap refresh
ruffle-update
nice -n 9 tldr -u
