#!/bin/bash

source $HOME/.nvm/nvm.sh

export OPENCODE_SERVER_PASSWORD=$(cat $HOME/.config/opencode-server/password.txt)

SYSTEMD_SERVICE_PATH="$HOME/.config/systemd/user/opencode-server.service"
read -r -d '' SYSTEMD_SERVICE << EOM
[Unit]
Description=Opencode Server

[Service]
Type=simple
ExecStart=/bin/bash -c "$HOME/scripts/opencode-server"
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
EOM

install() {
    mkdir -p $(dirname "$SYSTEMD_SERVICE_PATH")
    echo "$SYSTEMD_SERVICE" > "$SYSTEMD_SERVICE_PATH"

    systemctl --user daemon-reload
    systemctl --user enable opencode-server.service
    systemctl --user start opencode-server.service

    systemctl --user status opencode-server.service
}

if [[ $1 == install ]]; then
    install
elif [[ $1 == status ]]; then
    systemctl --user status opencode-server.service
elif [[ $1 == stop ]]; then
    systemctl --user stop opencode-server.service
    systemctl --user status opencode-server.service
elif [[ $1 == start ]]; then
    systemctl --user start opencode-server.service
    systemctl --user status opencode-server.service
else
    cd ~/docs/assistant
    opencode serve --hostname 0.0.0.0 2>&1 > $HOME/scripts/.logs/opencode-server.log
fi
