#!/bin/bash

path="$1"

if [ -z "$path" ]; then
    echo "Usage: $0 <path>"
    exit 1
fi

username=$(basename "$path")
password=$(pass "$path")

echo "Writing in 3..."
sleep 1
echo "Writing in 2..."
sleep 1
echo "Writing in 1..."
sleep 1

if [ "$2" != "--no-user" ]; then
    # TODO: Replace with wtype tool, e.g. wtype "$username"
    xdotool type --clearmodifiers "$username"
    # TODO: Replace with wtype tool, e.g. wtype "$(printf '\t')"
    xdotool key Tab
fi
# TODO: Replace with wtype tool, e.g. wtype "$password"
xdotool type --clearmodifiers "$password"

unset username password
