#!/bin/bash

passwords_dir="$HOME/.password-store/"

cd "$passwords_dir"

passwords=$(find -type f -name "*.gpg")
selected_password=$(echo "$passwords" | fzf --reverse)

if [[ -z "$selected_password" ]]; then
    exit 1
fi

selected_password=${selected_password:2}
selected_password=${selected_password%.gpg}

pass -c "$selected_password"
