#!/bin/bash

# Modify depending on the system
brightness_file="/sys/class/backlight/intel_backlight/brightness"
max_brightness_file="/sys/class/backlight/intel_backlight/max_brightness"

current_brightness=$(cat $brightness_file)
max_brightness=$(cat $max_brightness_file)
increment=500

case $1 in
    up)
        new_brightness=$((current_brightness + increment))
        ;;
    down)
        new_brightness=$((current_brightness - increment))
        ;;
    get)
        echo $((current_brightness * 100 / max_brightness))
        exit 0
        ;;
    set)
        new_brightness=$((max_brightness * $2 / 100))
        ;;
esac

if [ $new_brightness -gt $max_brightness ]; then
    new_brightness=$max_brightness
elif [ $new_brightness -lt 0 ]; then
    new_brightness=0
fi

echo $new_brightness > $brightness_file
