#!/bin/bash

# Prevent globbing
set -f

# Connect using vnc
remmina-connect() {
    remmina -c "vnc://$1"
}

is-hamachi-id() {
    [[ $1 =~ ^[0-9]{3}-[0-9]{3}-[0-9]{3}$ ]]
    return $?
}

is-ip() {
    [[ $1 =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]
    return $?
}

client_list=()

while read -r line; do
    should_be_id=$(echo "$line" | awk '{print $2}')
    name=""
    ip=""

    # Only connected clients
    if is-hamachi-id "$should_be_id"; then
        for item in $line; do
            if [[ "$item" == '*' ]]; then
                # Skip the connected status
                continue
            elif is-hamachi-id "$item"; then
                # Skip the id
                continue
            elif is-ip "$item"; then
                # This is the ip, finish the line
                ip="$item"
                client_list+=("$name|$ip")
                break
            else
                # Append to the name
                if [[ -z "$name" ]]; then
                    name="$item"
                else
                    name="$name $item"
                fi
            fi
        done

        name=""
        ip=""
    fi
done < <(hamachi list)

echo-client-list() {
    for item in "${client_list[@]}"; do
        echo "$item"
    done
}

if [[ -t 1 ]]; then
    ON_TTY=1
else
    ON_TTY=0
fi

select-client() {
    if [[ $ON_TTY -eq 1 ]]; then
        local selected=$(echo-client-list | fzf --prompt="Select a client: " --reverse --height=25)
    else
        local selected=$(echo-client-list | rofi -dmenu -i -l 25 -p "Select a client")
    fi
    echo "$selected"
}

selected=$(select-client)

if [[ -n "$selected" ]]; then
    ip=$(echo "$selected" | awk -F '|' '{print $2}')
    remmina-connect "$ip"
fi
