#!/bin/bash -x

DOWNLOAD_DIR="$HOME/tmp/.ruffle-update"
INSTALL_DIR="$HOME/.local/bin"
DOWNLOAD_LINK="https://github.com/ruffle-rs/ruffle/releases/download/nightly-$(date -u +%Y-%m-%d)/ruffle-nightly-$(date -u +%Y_%m_%d)-linux-x86_64.tar.gz"

if [ ! -d $DOWNLOAD_DIR ]; then
    mkdir $DOWNLOAD_DIR
fi

cd $DOWNLOAD_DIR
curl -LO $DOWNLOAD_LINK
tar -xvf $(basename $DOWNLOAD_LINK)
mv ruffle $INSTALL_DIR
