#!/bin/bash

PATH_OPTIONS=$(find ~/repos/oficina \
				 	~/repos/personales \
					~/storage/ \
				 	~/dotfiles \
				 	~/ \
					~/docs/ \
                    ~/docs/congregacion/ \
				 	~/docs/congregacion/discursos/publicos \
				 	~/docs/congregacion/discursos/ \
					~/docs/oficina \
				 	-mindepth 1 -maxdepth 1 -type d \
					-not -path '*\/.*' | sed 's/\/data\/data\/com.termux\/files\/home\///g')

TMUX_SESSIONS=$(tmux list-sessions -F "tmux:#{session_name}" 2> /dev/null)

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf "$PATH_OPTIONS\n$TMUX_SESSIONS"| fzf --reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $selected == "tmux:"* ]]; then
	tmux switch-client -t ${selected:5}
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_resurrect_dir="$HOME/.local/share/tmux/resurrect"
tmux_resurrect_last="last"

if ! tmux has-session -t=$selected_name 2> /dev/null; then
	if [[ -f "$tmux_resurrect_dir/$selected_name" ]]; then
		cd $tmux_resurrect_dir
		ln -sf $selected_name $tmux_resurrect_last
		$HOME/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh
		exit 0
	else
		tmux new-session -ds $selected_name -c $HOME/$selected
	fi
fi

tmux switch-client -t $selected_name
