#!/bin/bash

PATH_OPTIONS=$(find ~/repos/oficina \
				 	~/repos/personales \
				 	~/dotfiles \
				 	~/ \
					~/docs/ \
				 	~/docs/congregacion/discursos/publicos \
				 	~/docs/congregacion/discursos/ \
					~/docs/oficina \
				 	-mindepth 1 -maxdepth 1 -type d \
					-not -path '*/.*' | sed 's/\/home\/pablo\///g')

TMUX_SESSIONS=$(tmux list-sessions -F "#{session_name}" 2> /dev/null)
CURRENT_TMUX_SESSION=$(tmux display-message -p "#S" 2> /dev/null)
if [[ -n $TMUX_SESSIONS ]]; then
	if [[ -n $CURRENT_TMUX_SESSION ]]; then
		TMUX_SESSIONS=$(printf "%s\n" "$TMUX_SESSIONS" | awk -v cur="$CURRENT_TMUX_SESSION" '$0==cur {next} {print} END{ if (cur!="") print cur }')
	fi
	TMUX_SESSIONS=$(printf "%s\n" "$TMUX_SESSIONS" | sed 's/^/tmux:/')
fi

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(printf "$TMUX_SESSIONS\n$PATH_OPTIONS"| fzf --reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $selected == "tmux:"* ]]; then
	tmux switch-client -t ${selected:5}
	exit 0
fi

selected_name=$(basename "$selected" | tr . _)

tmux_resurrect_dir="$HOME/.local/share/tmux/resurrect"
tmux_resurrect_last="last"

if ! tmux has-session -t=$selected_name 2> /dev/null; then
	if [[ -f "$tmux_resurrect_dir/$selected_name" ]]; then
		cd $tmux_resurrect_dir
		ln -sf $selected_name $tmux_resurrect_last
		$HOME/.config/tmux/plugins/tmux-resurrect/scripts/restore.sh
		exit 0
	else
		tmux new-session -ds $selected_name -c /home/pablo/$selected
	fi
fi

tmux switch-client -t $selected_name
