#!/bin/bash

# UDISKIE_DMENU_IGNORE_LOOPS="true"

devices=$(udiskie-info -a)

if [[ -z $devices ]]; then
    echo "No devices found"
    exit 1
fi

if [[ ! -z $UDISKIE_DMENU_IGNORE_LOOPS ]]; then
    devices=$(echo "$devices" | grep -v "loop")
    echo $devices
fi


case $1 in
    mount)
        device=$(echo "$devices" | rofi -dmenu -i -p "Mount device" -l 10)
        if [ -z "$device" ]; then
            exit 0
        fi
        udiskie-mount $device
        ;;
    unmount)
        device=$(echo "$devices" | rofi -dmenu -i -p "Unmount device" -l 10)
        if [ -z "$device" ]; then
            exit 0
        fi
        udiskie-umount $device
        ;;
    *)
        echo "Usage: udiskie-dmenu [mount|unmount]"
        exit 1
        ;;
esac
