#!/bin/bash

case "$1" in
    "start")
        sudo systemctl start logmein-hamachi.service
        # sudo systemctl start zerotier-one.service
        systemctl status logmein-hamachi.service --no-pager
        # systemctl status zerotier-one.service --no-pager
        ;;
    "stop")
        sudo systemctl stop logmein-hamachi.service
        # sudo systemctl stop zerotier-one.service
        ;;
    "restart")
        sudo systemctl restart logmein-hamachi.service
        # sudo systemctl restart zerotier-one.service
        ;;
    "status")
        systemctl status logmein-hamachi.service --no-pager
        # systemctl status zerotier-one.service --no-pager
        ;;
    *)
        echo "Usage: $(basename "$0") {start|stop|restart|status}"
        exit 1
        ;;
esac
