#!/bin/bash

case "$1" in
    "start")
        # sudo systemctl start logmein-hamachi.service
        # # sudo systemctl start zerotier-one.service
        # systemctl status logmein-hamachi.service --no-pager
        # systemctl status zerotier-one.service --no-pager

        sudo /etc/init.d/logmein-hamachi start
        ;;
    "stop")
        # sudo systemctl stop logmein-hamachi.service
        # sudo systemctl stop zerotier-one.service

        sudo /etc/init.d/logmein-hamachi stop
        ;;
    "restart")
        # sudo systemctl restart logmein-hamachi.service
        # sudo systemctl restart zerotier-one.service
        sudo /etc/init.d/logmein-hamachi restart
        ;;
    "status")
        systemctl status logmein-hamachi.service --no-pager
        # systemctl status zerotier-one.service --no-pager
        ;;
    *)
        echo "Usage: $(basename "$0") {start|stop|restart|status}"
        exit 1
        ;;
esac
