#!/bin/bash

sessions=$(zellij ls -sn)

for session in $sessions; do
    read -p "Do you want to delete $session? [y/n] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        zellij d $session
    fi
done

